export const courses = [
    {
        id: 1,
        video: "https://www.youtube.com/embed/videoseries?si=xQfjnZco1KIfm6SH&amp;list=PLcJNiNfNwHEEfY7gZHdso0501m2XJFep-",
        title: "Live Speaking Practice",
        number_of_videos: 44,
        likes: 520,
        comments: 192,
        views: 563,
    },
    {
        id: 2,
        video: "https://www.youtube.com/embed/videoseries?si=Cq_u0Tb_dbGtvXQs&amp;list=PLcJNiNfNwHEGi9hJZOVX3dN0NkkceJe_u",
        title: "Helping Verbs Free Course",
        number_of_videos: 6,
        likes: 650,
        comments: 320,
        views: 784,
    },
    {
        id: 3,
        video: "https://www.youtube.com/embed/videoseries?si=--v-8nJsTzF506o9&amp;list=PLcJNiNfNwHEGOXMVhgGvOLNteUGe0XuJq",
        title: "English World with Kris Amerikos",
        number_of_videos: 22,
        likes: 340,
        comments: 122,
        views: 562,
    },
    {
        id: 4,
        video: "https://www.youtube.com/embed/videoseries?si=cbAC8RVCgUUpmKpP&amp;list=PLpuxPG4TUOR7bKmXgqM4ZdVT1-KSQfY3M",
        title: "Environment Issues and Current Affairs",
        number_of_videos: 10,
        likes: 250,
        comments: 152,
        views: 841,
    },
    {
        id: 5,
        video: "https://www.youtube.com/embed/videoseries?si=qcLMqql6nIk6UUxe&amp;list=PLpuxPG4TUOR5YRhp674ep0zqWe72bvhlb",
        title: "CSIR SO/ASO Exams",
        number_of_videos: 6,
        likes: 452,
        comments: 160,
        views: 400,
    },
    {
        id: 6,
        video: "https://www.youtube.com/embed/videoseries?si=jK9KgMhNfSmJc9ZI&amp;list=PLpuxPG4TUOR6QcB_fzOa642Bcue7OiXxG",
        title: "IB ACO Exams",
        number_of_videos: 11,
        likes: 410,
        comments: 181,
        views: 900,
    },
    {
        id: 7,
        video: "https://www.youtube.com/embed/videoseries?si=nRg4m5A3sZJma1na&amp;list=PLpuxPG4TUOR6d8DHmxEcdwOdZvkFc3S5X",
        title: "P2I Mentorship",
        number_of_videos: 2,
        likes: 470,
        comments: 142,
        views: 841,
    },
    {
        id: 8,
        video: "https://www.youtube.com/embed/videoseries?si=hyJI1UgB2hkQSuk5&amp;list=PLfqMhTWNBTe2B7jqoN28_WC6aRCg_WCRu",
        title: "Interview Questions",
        number_of_videos: 8,
        likes: 421,
        comments: 123,
        views: 632,
    },
    {
        id: 9,
        video: "https://www.youtube.com/embed/videoseries?si=JhJOF84VgJCjLtgt&amp;list=PLfqMhTWNBTe2-PBvkwbCAR6itzXcT1d45",
        title: "Puzzles for Software Engineers",
        number_of_videos: 7,
        likes: 420,
        comments: 192,
        views: 654,
    },
    {
        id: 10,
        video: "https://www.youtube.com/embed/videoseries?si=SILWPqn8hlWNMRVs&amp;list=PLfqMhTWNBTe0gqgFk-CUE-ktO5Cek1GdP",
        title: "Java Part-1 (Language)",
        number_of_videos: 24,
        likes: 580,
        comments: 172,
        views: 567,
    },
    {
        id: 11,
        video: "https://www.youtube.com/embed/videoseries?si=XdkSIK1WeT6AJ-Db&amp;list=PLfqMhTWNBTe0sPLFF91REaJQEteFZtLzA",
        title: "Java Part-2 (DSA)",
        number_of_videos: 24,
        likes: 670,
        comments: 222,
        views: 952,
    },
    {
        id: 12,
        video: "https://www.youtube.com/embed/videoseries?si=MUbdLktsuHNp3I9f&amp;list=PLXQpH_kZIxTUPxxJF1nnm9mGO3mjEydzw",
        title: "MERN Stack",
        number_of_videos: 7,
        likes: 420,
        comments: 213,
        views: 568,
    },
]